name: browservice thing

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  browservice_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node.js and npm...
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installing localtunnel...
        run: npm install -g localtunnel

      - name: Starting localtunnel and getting url...
        id: localtunnel_setup
        run: |
          lt --port 80 2>&1 | tee localtunnel_output.txt &
          cat localtunnel_output.txt
          wget -q -O - https://loca.lt/mytunnelpassword | tee ip.txt
          cat ip.txt

      - name: Installing browservice...
        run: |
          BROWSERVICE_DOWNLOAD_URL="https://github.com/ttalvitie/browservice/releases/download/v0.9.11.1/browservice-v0.9.11.1-x86_64.AppImage"
          curl -k -O "$BROWSERVICE_DOWNLOAD_URL" && chmod +x browservice-v0.9.11.1-x86_64.AppImage && ./browservice-v0.9.11.1-x86_64.AppImage

      - name: Keep alive
        run: sleep infinity
