name: browservice thing

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  browservice_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing node.js and npm...
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installing localtunnel...
        run: npm install -g localtunnel

      - name: Starting localtunnel and getting url...
        id: localtunnel_setup
        run: |
          curl https://loca.lt/mytunnelpassword
          lt --port 8080 2>&1 | tee localtunnel_output.txt &
          cat localtunnel_output.txt

      - name: Installing and configuring noVNC + qemu...
        run: |
          sudo apt update
          sudo apt install qemu-kvm qemu-system-x86
          curl -O https://dl.bobpony.com/windows/10/en-us_windows_10_22h2_x64.iso
          qemu-img create -f qcow2 win10.qcow2 20G
          nohup sudo qemu-system-x86_64 -accel kvm --cpu host -m 2G -smp 2 -hda win10.qcow2 -cdrom en-us_windows_10_22h2_x64.iso -boot d -display vnc=127.0.0.1:0,password=off -vga qxl &
          git clone https://www.github.com/novnc/noVNC
          cd noVNC && sudo ./utils/novnc_proxy --vnc 127.0.0.1:5900 --listen localhost:8080
